spring.application.name=api-gateway
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# opcional: definir o path da UI
# springdoc.swagger-ui.path=/swagger-ui.html

# Configuracoes de logging
logging.level.org.springframework.security=DEBUG
logging.level.com.fiap=DEBUG
logging.level.org.springframework=INFO

# /api-docs endpoint custom path
springdoc.api-docs.path=/api-doc

# URL do servico de user
user.service.url=${USER_SERVICE_URL:http://localhost:8085}



# Spring Boot
spring.main.allow-bean-definition-overriding=true
