spring:
  cloud:
    gateway:
      routes:
        - id: user-service-internal
          uri: ${services.user.uri}
          predicates:
            - Path=/api/internal/users/**
        - id: user-service
          uri: ${services.user.uri}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: parcel-service
          uri: ${services.parcel.uri}
          predicates:
            - Path=/api/parcels/**
          filters:
            - StripPrefix=1
