spring:
  config:
    activate:
      on-profile: docker

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

services:
  user:
    uri: http://user-service:8080
  parcel:
    uri: http://parcel-service:8080

server:
  port: 8080

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:test-secret}