spring:
  application:
    name: api-gateway

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/api_gateway_db}
    username: ${JDBC_DATABASE_USERNAME:apigateway}
    password: ${JDBC_DATABASE_PASSWORD:apigatewaypass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/dev-realm

logging:
  level:
    root: INFO
    com.fiap: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html